site_author: dhondta
site_name: "SploitKit - Devkit for building Metasploit-like consoles"
repo_url: https://github.com/dhondta/python-sploitkit
copyright: Copyright &copy; 2019-2023 Alexandre D'Hondt
docs_dir: pages
nav:
  - Introduction: index.md
  - 'Getting started': quickstart.md
  - Design: design.md
  - Classes:
    - classes/index.md
    - Entity: classes/entity.md
    - Console: classes/console.md
    - Command: classes/command.md
    - Module: classes/module.md
    - Datastore: classes/datastore.md
  - 'Base entities':
    - base/index.md
    - Consoles: base/consoles.md
    - Commands: base/commands.md
    - Models: base/models.md
  - 'Real-life examples':
    - 'DroneSploit': examples/dronesploit.md
extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:alexandre.dhondt@gmail.com
      name: Contact Alex
    - icon: fontawesome/brands/github
      link: https://github.com/dhondta
      name: Alex on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexandre-d-2ab2aa14/
      name: Alex on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/alex_dhondt
      name: Alex on Twitter
extra_css:
  - css/extra.css
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - toc.integrate
  logo: img/logo.png
  favicon: img/icon.png
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
